extends SceneTree
## Offline E2E regression for the Godot receiver against an INDEPENDENT contract
## derived from Blender's matrix_world (+ the C basis change), generated by
## tests/tools/generate_fixture.py and committed under tests/fixtures/.
##
## Verifies, per target mesh:
##   - node world transform  == C @ matrix_world @ C^-1
##   - world-space vertices  == C @ matrix_world @ local_vert  (as a point set)
##   - winding: the importer REVERSES Blender CCW -> Godot CW, so each Godot
##     triangle's true world normal must be OPPOSITE the C-mapped Blender
##     outward polygon normal (cross-dot < 0) on an outward-face mesh.
##   - inverse-transpose world normals align with C-mapped Blender loop normals.
##
## Run:  godot --headless --path . --script tests/test_e2e_fixture.gd

const ImporterScript := preload("res://addons/meshcore/importer.gd")
const ProtocolScript := preload("res://addons/meshcore/protocol.gd")
const FIXTURE := "res://tests/fixtures"

var importer = ImporterScript.new()
var root3d := Node3D.new()
var failing := 0
var ran := false

func _init() -> void:
	root3d.name = "MCVerifyRoot"
	root.add_child(root3d)

func _process(_delta: float) -> bool:
	if not ran:
		ran = true
		_run()
	quit(1 if failing > 0 else 0)
	return false

func _msg(s: String) -> void: print("[E2E] " + s)
func _fail(s: String) -> void: failing += 1; print("[E2E] FAIL: " + s)
func _v3(a: Array) -> Vector3: return Vector3(a[0], a[1], a[2])
func _clo(v: Vector3) -> String: return "(%.4f,%.4f,%.4f)" % [v.x, v.y, v.z]

func _run() -> void:
	var body: PackedByteArray = FileAccess.get_file_as_bytes(FIXTURE + "/scene.bin")
	var contract: Variant = JSON.parse_string(
		FileAccess.get_file_as_string(FIXTURE + "/contract.json"))
	if body.is_empty() or contract == null or typeof(contract) != TYPE_DICTIONARY:
		_fail("fixture missing/empty — run tests/tools/generate_fixture.py"); return
	var scene: Dictionary = ProtocolScript.decode_set(body)
	importer.apply_entities(scene.entities, root3d)
	var targets: Dictionary = contract["targets"]
	for name in targets:
		var t: Dictionary = targets[name]
		var node := _find(name)
		if node == null:
			_fail("node %s not created" % name); continue
		_check_transform(name, node, t)
		_check_world_verts(name, node, t)
		_check_winding_cw(name, node, t)
		_check_invtrans_normals(name, node, t)
	_msg("total failures: %d" % failing)

func _find(path: String) -> Node: return _find_by_name(root3d, path)

func _find_by_name(n: Node, path: String) -> Node:
	if n.name == path: return n
	for c in n.get_children():
		var r := _find_by_name(c, path)
		if r != null: return r
	return null

func _check_transform(name: String, node: Node, t: Dictionary) -> void:
	var wt: Dictionary = t["world_transform"]
	var gx: Transform3D = node.global_transform
	var exp_origin := _v3(wt["origin"])
	var exp_basis := Basis(_v3(wt["basis_c0"]), _v3(wt["basis_c1"]), _v3(wt["basis_c2"]))
	if gx.origin.distance_to(exp_origin) > 0.002:
		_fail("%s origin expected %s got %s" % [name, _clo(exp_origin), _clo(gx.origin)]); return
	for ax in [Vector3.RIGHT, Vector3.UP, Vector3.FORWARD]:
		var got: Vector3 = gx.basis * ax
		var exp: Vector3 = exp_basis * ax
		if got.distance_to(exp) > 0.004:
			_fail("%s basis image of %s expected %s got %s" % [name, _clo(ax), _clo(exp), _clo(got)]); return
	_msg("%s transform OK (origin %s)" % [name, _clo(gx.origin)])

func _check_world_verts(name: String, node: Node, t: Dictionary) -> void:
	var mi := node.get_node_or_null("Mesh") as MeshInstance3D
	if mi == null or mi.mesh == null:
		_fail("%s no applied mesh" % name); return
	var surf := mi.mesh.surface_get_arrays(0)
	var verts: PackedVector3Array = surf[Mesh.ARRAY_VERTEX]
	var gx: Transform3D = node.global_transform
	var actual := {}
	for v in verts:
		actual[_key(gx * v)] = true
	var missing := 0
	for e in (t["world_verts"] as Array):
		var ev := _v3(e)
		var found := actual.has(_key(ev))
		if not found:
			for k in actual.keys():
				if _v3(k.split(",")).distance_to(ev) < 0.004:
					found = true; break
		if not found:
			missing += 1
	if missing > 0:
		_fail("%s world verts: %d/%d unexpected" % [name, missing, (t["world_verts"] as Array).size()])
	else:
		_msg("%s world verts OK (%d unique)" % [name, actual.size()])

func _key(v: Vector3) -> String: return "%.4f,%.4f,%.4f" % [v.x, v.y, v.z]

func _mesh_triangles(name: String, node: Node) -> Array:
	var mi := node.get_node_or_null("Mesh") as MeshInstance3D
	if mi == null or mi.mesh == null: return []
	var surf := mi.mesh.surface_get_arrays(0)
	var verts: PackedVector3Array = surf[Mesh.ARRAY_VERTEX]
	var idx: PackedInt32Array = surf[Mesh.ARRAY_INDEX] if surf[Mesh.ARRAY_INDEX] != null else PackedInt32Array()
	var gx: Transform3D = node.global_transform
	var loop := idx.size() if idx.size() > 0 else verts.size()
	var tris := []
	for i in range(0, loop, 3):
		var a := gx * (verts[idx[i] if idx.size() > 0 else i])
		var b := gx * (verts[idx[i+1] if idx.size() > 0 else i+1])
		var c := gx * (verts[idx[i+2] if idx.size() > 0 else i+2])
		tris.append((b - a).cross(c - a).normalized())
	return tris

func _check_winding_cw(name: String, node: Node, t: Dictionary) -> void:
	var exp_tri: Array = t.get("world_tri_normals", [])
	var exp_face: Array = t.get("world_face_normals", [])
	if exp_tri.is_empty() and exp_face.is_empty():
		_msg("%s no world_tri_normals in contract; skip winding" % name); return
	var tris := _mesh_triangles(name, node)
	if tris == null or tris.is_empty(): _fail("%s no mesh for winding" % name); return
	var exp_n := []
	for e in exp_tri: exp_n.append(_v3(e))
	# exact index correspondence (importer emits triangles in polygon/fan order)
	if exp_n.size() != tris.size():
		_fail("%s winding mismatch: %d godot tris vs %d contr tri normals" % [name, tris.size(), exp_n.size()]); return
	var wrong := 0
	for i in tris.size():
		var fn: Vector3 = tris[i]
		var en: Vector3 = exp_n[i]
		var d := fn.dot(en)
		if d > -0.5:  # should be opposite (Godot CW vs Blender CCW)
			wrong += 1
			if wrong <= 3:
				_msg("  %s tri%d normal %s dot(contr)=%.3f (want <= -0.5)" % [name, i, _clo(fn), d])
	if wrong > 0:
		_fail("%s winding: %d/%d triangles not Godot-CW (should be opposite Blender CCW)" % [name, wrong, tris.size()])
	else:
		_msg("%s winding OK (%d triangles Godot-CW, opposite Blender)" % [name, tris.size()])

func _check_invtrans_normals(name: String, node: Node, t: Dictionary) -> void:
	var exp_list: Array = t.get("world_loop_normals", [])
	if exp_list.is_empty():
		_msg("%s no world_loop_normals; skip inv-transpose" % name); return
	var mi := node.get_node_or_null("Mesh") as MeshInstance3D
	if mi == null or mi.mesh == null: _fail("%s no mesh for normals" % name); return
	var nrm: PackedVector3Array = mi.mesh.surface_get_arrays(0)[Mesh.ARRAY_NORMAL]
	if nrm.is_empty(): _msg("%s no normal array; skip" % name); return
	var inv_t: Basis = node.global_transform.basis.inverse().transposed()
	var exp_n := []
	for e in exp_list: exp_n.append(_v3(e))
	var bad := 0
	for n in nrm:
		var w := (inv_t * n).normalized()
		var best := -1.0
		for en in exp_n:
			var d := w.dot(en)
			if d > best: best = d
		if best < 0.98:
			bad += 1
	if bad > 0:
		_fail("%s inv-transpose normals: %d/%d misaligned" % [name, bad, nrm.size()])
	else:
		_msg("%s inv-transpose normals OK (%d)" % [name, nrm.size()])